# Generated by Django 3.2.5 on 2021-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
