# Generated by Django 3.2.5 on 2021-09-23 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.IntegerField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
