# Generated by Django 3.2.5 on 2021-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_user_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
