# Generated by Django 3.2.5 on 2021-09-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0003_alter_user_user_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='ott/static/media/myprofile.png', upload_to='ott/static/media/images_users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pw',
            field=models.TextField(max_length=100),
        ),
    ]
